version: '3.8'

services:

  seidor-car-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seidor-car-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    external_links:
      - postgres_db

  postgres_db:
    image: postgres:9-alpine
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres_db

volumes:
  seidor-car-app:
    name: seidor-valume
  pgadmin:
    name: pgadmin
  postgres:
    name: seidor-db